server:
  host: 0.0.0.0
  port: 8080
  timeout:
    server: 30s
    read: 15s
    write: 10s
    idle: 5s
  maxRequestBodySize: 64KB
redis:
  db: 0
  ping:
    enable: true
  module:
    expiration: 720h #30d
log:
  format: json
